name: Build and publish
on:
  push:
    branches: ["main", "beta"]

jobs:
  deploy:
    name: Release Command line
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Publish to npm
        run: echo 'to change with the real command'
      - name: Get Semantic Release current version
        id: semantic_version
        run: |
          VERSION=`node -p "require('./package.json').devDependencies['semantic-release']"`
          echo "::set-output name=version::$VERSION"
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@767cc0b0cd610ffb1ffee1b36a9b39120adc5f80
        id: semantic
        with:
          semantic_version: ${{ steps.semantic_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      